export const messages = {
	'es': {
		'A profile with the same type already exists': 'Ya existe un perfil con ese tipo',
		'A plan with the same name already exists': 'Ya existe un plan con ese nombre',
		'Actions': 'Acciones',
		'Add': 'Agregar',
		'Address': 'Dirección',
		'Admin': 'Administración',
		'A company with the same name already exists': 'Ya existe un empresa con ese nombre',
		'An user with the same email or username already exists': 'Ya existe un usuario con ese correo o usuario',
		'Are you sure you want to delete this?': '¿Está seguro de que desea eliminar los registros?',
		'Can create challenges': 'Puede crear retos',
		'Can send email remainders': 'Puede enviar recordatorios por correo',
		'Can view analytics': 'Puede ver estadísticas',
		'Can Login': 'Puede iniciar sesión',
		'Cannot delete companies with users.': 'No se puede eliminar empresas con usuarios asociados.',
		'Cannot delete profiles with users.': 'No se puede eliminar perfiles con usuarios asociados.',
		'Can not delete a plan that companies use.': 'No se puede eliminar un plan que una empresa utiliza',
		'Cancel': 'Cancelar',
		'Change Password': 'Cambiar contraseña',
		'Create': 'Crear',
		'Create Company': 'Crear empresa',
		'Create Plan': 'Crear plan',
		'Create Profile': 'Crear perfil',
		'Create User': 'Crear usuario',
		'Could not create a company': 'No se pudo crear un empresa',
		'Could not create an user': 'No se pudo crear un usuario',
		'Could not find a company with that id': 'No existe esa empresa',
		'Dashboard': 'Panel de control',
		'Delete': 'Eliminar',
		'Delete Companies': 'Eliminar empresas',
		'Delete Plans': 'Eliminar planes',
		'Delete Profiles': 'Eliminar perfiles',
		'Delete Users': 'Eliminar usuarios',
		'Description': 'Descripción',
		'Edit': 'Editar',
		'Edit Company': 'Editar empresa',
		'Edit Plan': 'Editar plan',
		'Edit Profile': 'Editar perfil',
		'Edit User': 'Editar usuario',
		'Email': 'Email',
		'Fee': 'Cuota',
		'Fee Type': 'Tipo de cuota',
		'Fee Value': 'Valor de cuota',
		'Filter by Name': 'Filtrar por nombre',
		'Filter by Name or Address': 'Filtrar por nombre o dirección',
		'Filter by Name, Email or Username': 'Filtrar por nombre, correo o usuario',
		'Filter by Company': 'Filtrar por empresa',
		'Filter by Plan': 'Filtrar por plan',
		'Filter by Profile': 'Filtrar por perfil',
		'Filter by Type': 'Filtrar por tipo',
		'Free': 'Gratis',
		'Free Service': 'Servicio gratuito',
		'Graphs': 'Indicadores',
		'ID': 'Identificación',
		'Invalid Token': 'Token inválido',
		'Is not a valid email address': 'No es una dirección de correo correcta',
		'Is Mobile User': 'Usuario aplicación',
		'Is Super Admin': 'Super usuario',
		'jwt expired': 'La sesión expiró',
		'logout': 'cerrar sesión',
		'Login': 'Inicia sesión',
		'Logo': 'Logo',
		'monthly': 'mensual',
		'Message': 'Mensaje',
		'Monthly': 'Mensual',
		'Name': 'Nombre',
		'No companies were deleted.': 'No se pudo eliminar empresa(s).',
		'of': 'de',
		'company': 'empresa',
		'Company': 'Empresa',
		'Company created': 'Empresa creada',
		'Company deleted': 'Empresa eliminada',
		'Company updated': 'Empresa actualizada',
		'Company Logo': 'Logo de empresa',
		'Companies': 'Empresas',
		'Password': 'Contraseña',
		'Permissions': 'Permisos',
		'Phones': 'Teléfonos',
		'plan': 'plan',
		'plans': 'plans',
		'Plan': 'Plan',
		'Plan created': 'Plan creado',
		'Plan deleted': 'Plan eliminado',
		'Plan updated': 'Plan actualizado',
		'Plans': 'Planes',
		'Please put your username or your email.': 'Ingresa tu usuario o tu correo.',
		'Please put a password.': 'Ingresa tu contraseña.',
		'Profile': 'Perfil',
		'Profile created': 'Perfil creado',
		'Profile deleted': 'Perfil eliminado',
		'Profile updated': 'Perfil actualizado',
		'Profiles': 'Perfiles',
		'Remove': 'Eliminar',
		'selected': 'seleccionados',
		'Save': 'Guardar',
		'Send': 'Enviar',
		'Should Change Password': 'Debe cambiar contraseña',
		'The following companies will not be deleted since they have users:': 'Las siguientes empresas no podrán ser eliminadas ya que tienen usuarios asociados:',
		'The following profiles will not be deleted since they have users:': 'Los siguientes perfiles no podrán ser eliminados ya que tienen usuarios asociados:',
		'The companies were deleted.': 'Las empresas fueron eliminados exitosamente.',
		'The plans were deleted.': 'Los planes fueron eliminados exitosamente.',
		'The profiles were deleted.': 'Los perfiles fueron eliminados exitosamente.',
		'The users were deleted.': 'Los usuarios fueron eliminados exitosamente.',
		'The username or password don\'t match': 'El usuario y la contraseña no coinciden con nuestros registros.',
		'The session has expired, please login again.': 'La sesión expiró, por favor ingresa tus credenciales nuevamente.',
		'There was an error with the access token.': 'Ocurrió un error con el token de acceso.',
		'This field is required.': 'Este campo es obligatorio',
		'This company has users associated with': 'La empresa tiene usuarios asociados.',
		'Type': 'Tipo',
		'Upload Logo': 'Subir logo',
		'user or user@brandtreat.com': 'usuario o usuario@brandtreat.com',
		'User created': 'Usuario creado',
		'User deleted': 'Usuario eliminado',
		'User updated': 'Usuario actualizado',
		'Users': 'Usuarios',
		'Username': 'Usuario',
		'Username or email': 'Usuario o correo electrónico',
		'Value': 'Valor',
		'VAT': 'RUC',
		'yearly': 'anual',
		'Yearly': 'Anual',
		'You have been successfully logged in.': 'Has iniciado sesión correctamente.',
		'You must send the username and the password': 'Ingresa tu usario y contraseña.',
		'You have been successfully logged out.': "Has cerrado sesión correctamente.",
	},
	'en': {}
}